version: '3'
services:
  server:
    container_name: server
    build:
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - IMAGES_PATH=/media
    ports:
      - "8000:8000"
    volumes:
      - data:/media

volumes:
  data:
    external: true
