version: '3'
services:
  db:
    image: mongo:5.0.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.runCommand('ping').ok" ]
      interval: 30s
      timeout: 10s
      retries: 5
  app:
    build:
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "8000:8000"
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  mongo-data:
