version: '3'
services:
  db:
    container_name: db
    image: mongo:5.0.0
    ports:
      - "27017:27017"
    volumes:
      - data:/db
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.runCommand('ping').ok" ]
      interval: 30s
      timeout: 10s
      retries: 5
  app:
    container_name: app
    build:
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "8000:8000"
    volumes:
      - data:/media
    depends_on:
      - db

volumes:
  data:
