version: '3'
services:
  db:
    image: mongo:5.0.0
    environment:
      - MONGO_PORT=27017
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.runCommand('ping').ok" ]
      interval: 30s
      timeout: 10s
      retries: 5
  app:
    build: .
    environment:
      - NODE_ENV=production
    ports:
      - "8080:8080"
    depends_on:
      - db
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:${APP_PORT}/health"
        ]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  mongo-data:
